### ISSUE TITLE
SVG i Internet Explorer

### ISSUE THREAD

**Issue by AntonKL** [Defiso/Defiso-webpage#16]

**Comment by frystpingvin** [comment]
Kan ordna det.

Vi bör kanske försöka ordna något system för kvalitetskontroll? Är ju knappast första gången vi råkar skicka saker som inte ser bra ut i IE :) 

Kan man ha färdiga issues-templates i github t.ex.?

**Comment by frystpingvin** [comment]
Nu ska det vara löst (iaf i E11 W7, den enda webbläsaren som jag kan kolla i Browserstack som hade problemet). För över alla filer i /illustrations/ så ska det se bra ut
